# Site settings
title: Divyanshu Thakur
name: Divyanshu Thakur
tagline: 'Open Source Enthusiast'
#subtitle: Learnings, Ramblings and Rants. In that order.
email: divyanshufs01@gmail.com
description: >
  A blog to keep track of my GSoC progress
baseurl: ""
url: "https://divyanshu132.github.io/"
github_username:  divyanshu132
disqus_baseurl: "https://divyanshu132.github.io/"
disqus_shortname: https-divyanshu132-github-io
permalink: :title
ga_tracking_id: "UA-82647777-1"
excerpt_seperator: <!-break->


# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true
version: 1.0.1

defaults:
  -
    scope:
      path: ""
    values:
      author: "Divyanshu Thakur"


# About/contact
author:
  name:             Divyanshu Thakur
  github:           divyanshu132
  email:            divyanshufs01@gmail.com
  linkedin:         divyanshu132
  gravatar_md5:     2850fb9344edf290ac29710b26a9c2d0

# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
